/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a user, persist the session, and send an email verification notification. */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Authenticate a user with email and password and persist the session. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the currently authenticated user from the session. */
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/verify/{id}/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Verify the authenticated user email address with a signed URL. */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/verification-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send an email verification notification to the authenticated unverified user. */
        post: operations["sendEmailVerificationNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Invalidate the current authenticated session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-column-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List supported custom column types (master data). */
        get: operations["indexCustomColumnTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List custom tables visible to the authenticated user. */
        get: operations["indexCustomTables"];
        put?: never;
        /** @description Create a new custom table owned by the authenticated user. */
        post: operations["storeCustomTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve a single custom table by UUID. */
        get: operations["showCustomTable"];
        put?: never;
        post?: never;
        /** @description Delete a custom table and all its columns / rows. */
        delete: operations["destroyCustomTable"];
        options?: never;
        head?: never;
        /** @description Update name or description of a custom table. */
        patch: operations["updateCustomTable"];
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List columns of a custom table. */
        get: operations["indexCustomColumns"];
        put?: never;
        /** @description Create a new column on a custom table. */
        post: operations["storeCustomColumn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/columns/{column_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve a single custom column by UUID. */
        get: operations["showCustomColumn"];
        put?: never;
        post?: never;
        /** @description Delete a custom column. */
        delete: operations["destroyCustomColumn"];
        options?: never;
        head?: never;
        /** @description Update attributes of an existing custom column. */
        patch: operations["updateCustomColumn"];
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List rows of a custom table. */
        get: operations["indexCustomRows"];
        put?: never;
        /** @description Create a new row on a custom table. */
        post: operations["storeCustomRow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/rows/{row_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve a single custom row by UUID. */
        get: operations["showCustomRow"];
        put?: never;
        post?: never;
        /** @description Delete a custom row. */
        delete: operations["destroyCustomRow"];
        options?: never;
        head?: never;
        /** @description Update values of a custom row. */
        patch: operations["updateCustomRow"];
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/rows/{row_uuid}/cells/{column_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update a single cell value on a custom row. */
        patch: operations["updateCustomCell"];
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/rows/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Search custom rows with typed filters, column sort, and pagination. */
        post: operations["searchCustomRows"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List custom table members. Owner role is required. */
        get: operations["indexCustomTableMembers"];
        put?: never;
        /** @description Share a custom table with a user or assign a member role. Owner role is required. */
        post: operations["storeCustomTableMember"];
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update a custom table member role or transfer owner role. Owner role is required. */
        patch: operations["updateCustomTableMember"];
        trace?: never;
    };
    "/api/custom-tables/{table_uuid}/members/{user_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a custom table member. Owner role is required. */
        delete: operations["destroyCustomTableMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List dashboards visible to the authenticated user. */
        get: operations["indexDashboards"];
        put?: never;
        /** @description Create a dashboard. The authenticated user becomes the owner. */
        post: operations["storeDashboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/{dashboard_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Show a dashboard the authenticated user can access. */
        get: operations["showDashboard"];
        put?: never;
        post?: never;
        /** @description Delete a dashboard. Owner role is required. */
        delete: operations["destroyDashboard"];
        options?: never;
        head?: never;
        /** @description Update a dashboard. Owner role is required. */
        patch: operations["updateDashboard"];
        trace?: never;
    };
    "/api/dashboards/{dashboard_uuid}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List dashboard members. Owner role is required. */
        get: operations["indexDashboardMembers"];
        put?: never;
        /** @description Share a dashboard with a user or assign a member role. Owner role is required. */
        post: operations["storeDashboardMember"];
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update a dashboard member role or transfer owner role. Owner role is required. */
        patch: operations["updateDashboardMember"];
        trace?: never;
    };
    "/api/dashboards/{dashboard_uuid}/members/{user_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a dashboard member. Owner role is required. */
        delete: operations["destroyDashboardMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/dashboards/{share_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Show a public (unlisted/public) dashboard by its share token. No authentication required. */
        get: operations["showPublicDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/dashboards/{share_token}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compute and return live widget results for a public dashboard. No authentication required. */
        get: operations["showPublicDashboardData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/{dashboard_uuid}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compute and return live widget results for a dashboard, using the owner data access. */
        get: operations["showDashboardData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/{dashboard_uuid}/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List widgets of a dashboard the authenticated user can access. */
        get: operations["indexWidgets"];
        put?: never;
        /** @description Create a widget. Owner or editor role is required. */
        post: operations["storeWidget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/{dashboard_uuid}/widgets/{widget_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a widget. Owner or editor role is required. */
        delete: operations["destroyWidget"];
        options?: never;
        head?: never;
        /** @description Update a widget. Owner or editor role is required. */
        patch: operations["updateWidget"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API health check endpoint placeholder. */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomTable: {
            /** Format: uuid */
            table_uuid: string;
            name: string | null;
            description: string | null;
            created_at: string | null;
            updated_at: string | null;
        };
        CustomTableOverview: {
            /** Format: uuid */
            table_uuid: string;
            name: string | null;
            description: string | null;
            /** @example owner */
            role: string;
            owner: {
                /** Format: uuid */
                user_uuid: string;
                name: string | null;
                email: string | null;
            } | null;
            member_count: number;
            column_count: number;
            row_count: number;
            created_at: string | null;
            updated_at: string | null;
        };
        CustomColumn: {
            /** Format: uuid */
            column_uuid: string;
            name: string | null;
            type: string | null;
            default_value: string | null;
            sort_order: number;
            is_required: boolean;
            options: {
                /** Format: uuid */
                option_uuid: string;
                label: string;
                value: string;
                sort_order: number;
            }[];
            constraints: components["schemas"]["CustomColumnConstraint"][];
            created_at: string | null;
            updated_at: string | null;
        };
        CustomColumnConstraint: {
            /** Format: uuid */
            constraint_uuid: string;
            /** @example min */
            code: string;
            parameters: {
                [key: string]: unknown;
            } | null;
        };
        CustomColumnConstraintInput: {
            /**
             * @example min
             * @enum {string}
             */
            code: "min" | "max" | "integer" | "decimal" | "min_length" | "max_length" | "contains" | "regex" | "before" | "after" | "in_options";
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        CustomRow: {
            /** Format: uuid */
            row_uuid: string;
            values: {
                [key: string]: (string | null) | (boolean | null);
            };
            created_at: string | null;
            updated_at: string | null;
        };
        CustomTableMember: {
            /**
             * Format: uuid
             * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
             */
            user_uuid: string;
            /**
             * @example viewer
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
        };
        CustomTableMemberInput: {
            /**
             * Format: uuid
             * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
             */
            user_uuid: string;
            /**
             * @example viewer
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
        };
        DashboardOwner: {
            /**
             * Format: uuid
             * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
             */
            user_uuid: string;
            name: string | null;
            /** Format: email */
            email: string | null;
        } | null;
        Dashboard: {
            /** Format: uuid */
            dashboard_uuid: string;
            name: string | null;
            description: string | null;
            /**
             * @example private
             * @enum {string}
             */
            visibility: "private" | "restricted" | "internal" | "unlisted" | "public";
            /**
             * @example owner
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
            owner: components["schemas"]["DashboardOwner"];
            /**
             * Format: uuid
             * @description Token for unlisted/public access via /api/public/dashboards/{share_token}.
             */
            share_token: string | null;
            created_at: string | null;
            updated_at: string | null;
        };
        DashboardOverview: {
            /** Format: uuid */
            dashboard_uuid: string;
            name: string | null;
            description: string | null;
            /**
             * @example private
             * @enum {string}
             */
            visibility: "private" | "restricted" | "internal" | "unlisted" | "public";
            /**
             * @example owner
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
            owner: components["schemas"]["DashboardOwner"];
            /** @example 1 */
            member_count: number;
            created_at: string | null;
            updated_at: string | null;
        };
        DashboardMember: {
            /**
             * Format: uuid
             * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
             */
            user_uuid: string;
            /**
             * @example viewer
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
        };
        DashboardMemberInput: {
            /**
             * Format: uuid
             * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
             */
            user_uuid: string;
            /**
             * @example viewer
             * @enum {string}
             */
            role: "owner" | "editor" | "viewer";
        };
        DashboardInput: {
            /** @example 営業ダッシュボード */
            name: string;
            description?: string | null;
            /**
             * @example private
             * @enum {string}
             */
            visibility?: "private" | "restricted" | "internal" | "unlisted" | "public";
        };
        DashboardUpdateInput: {
            name?: string;
            description?: string | null;
            /** @enum {string} */
            visibility?: "private" | "restricted" | "internal" | "unlisted" | "public";
        };
        WidgetFilter: {
            /** Format: uuid */
            column_uuid: string;
            /** @example equals */
            operator: string;
            value: string | null;
            value_to: string | null;
        };
        WidgetFilterInput: {
            /** Format: uuid */
            column_uuid: string;
            /** @enum {string} */
            operator: "equals" | "not_equals" | "contains" | "starts_with" | "gt" | "gte" | "lt" | "lte" | "between" | "before" | "after" | "is_empty" | "is_not_empty" | "is_true" | "is_false";
            value?: string | null;
            value_to?: string | null;
        };
        Widget: {
            /** Format: uuid */
            widget_uuid: string;
            /** Format: uuid */
            source_table_uuid: string;
            /**
             * @example kpi
             * @enum {string}
             */
            type: "kpi" | "table" | "list" | "bar" | "line" | "pie";
            title: string | null;
            metric: string | null;
            /** Format: uuid */
            group_by_column_uuid: string | null;
            /** Format: uuid */
            value_column_uuid: string | null;
            /** Format: uuid */
            sort_column_uuid: string | null;
            sort_direction: string | null;
            limit: number | null;
            /** @example 0 */
            position: number;
            filters: components["schemas"]["WidgetFilter"][];
            created_at: string | null;
            updated_at: string | null;
        };
        WidgetInput: {
            /** Format: uuid */
            source_table_uuid: string;
            /** @enum {string} */
            type: "kpi" | "table" | "list" | "bar" | "line" | "pie";
            title?: string | null;
            /** @enum {string|null} */
            metric?: "count" | "sum" | "avg" | "min" | "max" | null;
            /** Format: uuid */
            group_by_column_uuid?: string | null;
            /** Format: uuid */
            value_column_uuid?: string | null;
            /** Format: uuid */
            sort_column_uuid?: string | null;
            /** @enum {string|null} */
            sort_direction?: "asc" | "desc" | null;
            limit?: number | null;
            position?: number | null;
            filters?: components["schemas"]["WidgetFilterInput"][];
        };
        WidgetResult: {
            /** Format: uuid */
            widget_uuid: string;
            /** @enum {string} */
            type: "kpi" | "table" | "list" | "bar" | "line" | "pie";
            title: string | null;
            /** @description All widget types share this shape. Unused fields are null (value) or empty arrays (columns/rows/groups). */
            result: {
                value: number | null;
                columns: {
                    /** Format: uuid */
                    column_uuid: string;
                    name: string | null;
                    type: string | null;
                }[];
                rows: {
                    /** Format: uuid */
                    row_uuid: string;
                    values: Record<string, never>;
                }[];
                groups: {
                    label: string;
                    value: number | null;
                }[];
            };
        };
        WidgetUpdateInput: {
            /** @enum {string} */
            type?: "kpi" | "table" | "list" | "bar" | "line" | "pie";
            title?: string | null;
            /** @enum {string|null} */
            metric?: "count" | "sum" | "avg" | "min" | "max" | null;
            /** Format: uuid */
            group_by_column_uuid?: string | null;
            /** Format: uuid */
            value_column_uuid?: string | null;
            /** Format: uuid */
            sort_column_uuid?: string | null;
            /** @enum {string|null} */
            sort_direction?: "asc" | "desc" | null;
            limit?: number | null;
            position?: number | null;
            filters?: components["schemas"]["WidgetFilterInput"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Example User */
                    name: string;
                    /**
                     * Format: email
                     * @example member@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example password
                     */
                    password: string;
                    /**
                     * Format: password
                     * @example password
                     */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Registration successful. Please verify your email address. */
                        message: string;
                        data: {
                            user: {
                                /**
                                 * Format: uuid
                                 * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
                                 */
                                user_uuid: string;
                                /** @example Example User */
                                name: string;
                                /**
                                 * Format: email
                                 * @example member@example.com
                                 */
                                email: string;
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example member@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example password
                     */
                    password: string;
                    /** @example false */
                    remember?: boolean;
                };
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login successful. */
                        message: string;
                        data: {
                            user: {
                                /**
                                 * Format: uuid
                                 * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
                                 */
                                user_uuid: string;
                                /** @example Example User */
                                name: string;
                                /**
                                 * Format: email
                                 * @example member@example.com
                                 */
                                email: string;
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Current user retrieved. */
                        message: string;
                        data: {
                            user: {
                                /**
                                 * Format: uuid
                                 * @example 019a0367-43e2-73dd-bd68-9cb1d2efea70
                                 */
                                user_uuid: string;
                                /** @example Example User */
                                name: string;
                                /**
                                 * Format: email
                                 * @example member@example.com
                                 */
                                email: string;
                            };
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal signed verification identifier. */
                id: number;
                /** @description Signed verification hash. */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Email verified. */
                        message: string;
                        /** @example [] */
                        data: string[];
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Invalid verification link */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    sendEmailVerificationNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification link sent */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Verification link sent. */
                        message: string;
                        /** @example [] */
                        data: string[];
                    };
                };
            };
            /** @description Already verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexCustomColumnTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom column types retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom column types retrieved. */
                        message: string;
                        data: {
                            custom_column_types: {
                                /** @example text */
                                code: string;
                                /** @example Text */
                                name: string;
                                description: string | null;
                            }[];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexCustomTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom tables retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom tables retrieved. */
                        message: string;
                        data: {
                            custom_tables: components["schemas"]["CustomTableOverview"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeCustomTable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Tasks */
                    name: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Custom table created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom table created. */
                        message: string;
                        data: {
                            custom_table: components["schemas"]["CustomTable"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showCustomTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom table retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom table retrieved. */
                        message: string;
                        data: {
                            custom_table: components["schemas"]["CustomTable"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyCustomTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom table deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateCustomTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Renamed */
                    name?: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Custom table updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom table updated. */
                        message: string;
                        data: {
                            custom_table: components["schemas"]["CustomTable"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexCustomColumns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom columns retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom columns retrieved. */
                        message: string;
                        data: {
                            custom_columns: components["schemas"]["CustomColumn"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeCustomColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Title */
                    name: string;
                    /**
                     * @example text
                     * @enum {string}
                     */
                    type: "text" | "number" | "boolean" | "date" | "select";
                    default_value?: string | null;
                    /** @example 0 */
                    sort_order?: number;
                    /** @example false */
                    is_required?: boolean;
                    options?: {
                        label: string;
                        value: string;
                        sort_order?: number | null;
                    }[] | null;
                    constraints?: components["schemas"]["CustomColumnConstraintInput"][] | null;
                };
            };
        };
        responses: {
            /** @description Custom column created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom column created. */
                        message: string;
                        data: {
                            custom_column: components["schemas"]["CustomColumn"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showCustomColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                column_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom column retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom column retrieved. */
                        message: string;
                        data: {
                            custom_column: components["schemas"]["CustomColumn"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyCustomColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                column_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom column deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateCustomColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                column_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    type?: "text" | "number" | "boolean" | "date" | "select";
                    default_value?: string | null;
                    sort_order?: number;
                    is_required?: boolean;
                    options?: {
                        label: string;
                        value: string;
                        sort_order?: number | null;
                    }[];
                    constraints?: components["schemas"]["CustomColumnConstraintInput"][];
                };
            };
        };
        responses: {
            /** @description Custom column updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom column updated. */
                        message: string;
                        data: {
                            custom_column: components["schemas"]["CustomColumn"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexCustomRows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom rows retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom rows retrieved. */
                        message: string;
                        data: {
                            custom_rows: components["schemas"]["CustomRow"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeCustomRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    values?: {
                        [key: string]: (string | null) | (boolean | null);
                    };
                };
            };
        };
        responses: {
            /** @description Custom row created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom row created. */
                        message: string;
                        data: {
                            custom_row: components["schemas"]["CustomRow"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showCustomRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                row_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom row retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom row retrieved. */
                        message: string;
                        data: {
                            custom_row: components["schemas"]["CustomRow"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyCustomRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                row_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom row deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateCustomRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                row_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    values: {
                        [key: string]: (string | null) | (boolean | null);
                    };
                };
            };
        };
        responses: {
            /** @description Custom row updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom row updated. */
                        message: string;
                        data: {
                            custom_row: components["schemas"]["CustomRow"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateCustomCell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                row_uuid: string;
                column_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: (string | null) | (number | null) | (boolean | null);
                };
            };
        };
        responses: {
            /** @description Custom cell updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    searchCustomRows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom table UUID. */
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Custom rows searched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom rows searched. */
                        message: string;
                        data: {
                            custom_rows: components["schemas"]["CustomRow"][];
                            pagination: {
                                /** @example 1 */
                                current_page: number;
                                /** @example 50 */
                                per_page: number;
                                /** @example 1 */
                                total: number;
                                /** @example 1 */
                                last_page: number;
                            };
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexCustomTableMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom table members retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom table members retrieved. */
                        message: string;
                        data: {
                            custom_table_members: components["schemas"]["CustomTableMember"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeCustomTableMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTableMemberInput"];
            };
        };
        responses: {
            /** @description Custom table member saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom table member saved. */
                        message: string;
                        data: {
                            custom_table_member: components["schemas"]["CustomTableMember"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateCustomTableMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTableMemberInput"];
            };
        };
        responses: {
            /** @description Custom table member saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Custom table member saved. */
                        message: string;
                        data: {
                            custom_table_member: components["schemas"]["CustomTableMember"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyCustomTableMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_uuid: string;
                user_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom table member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexDashboards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboards retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboards retrieved. */
                        message: string;
                        data: {
                            dashboards: components["schemas"]["DashboardOverview"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardInput"];
            };
        };
        responses: {
            /** @description Dashboard created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard created. */
                        message: string;
                        data: {
                            dashboard: components["schemas"]["Dashboard"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard retrieved. */
                        message: string;
                        data: {
                            dashboard: components["schemas"]["Dashboard"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardUpdateInput"];
            };
        };
        responses: {
            /** @description Dashboard updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard updated. */
                        message: string;
                        data: {
                            dashboard: components["schemas"]["Dashboard"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexDashboardMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard members retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard members retrieved. */
                        message: string;
                        data: {
                            dashboard_members: components["schemas"]["DashboardMember"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeDashboardMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardMemberInput"];
            };
        };
        responses: {
            /** @description Dashboard member saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard member saved. */
                        message: string;
                        data: {
                            dashboard_member: components["schemas"]["DashboardMember"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateDashboardMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardMemberInput"];
            };
        };
        responses: {
            /** @description Dashboard member saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard member saved. */
                        message: string;
                        data: {
                            dashboard_member: components["schemas"]["DashboardMember"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyDashboardMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
                user_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showPublicDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard retrieved. */
                        message: string;
                        data: {
                            dashboard: components["schemas"]["Dashboard"];
                        };
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showPublicDashboardData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data computed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard data computed. */
                        message: string;
                        data: {
                            widgets: components["schemas"]["WidgetResult"][];
                        };
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    showDashboardData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data computed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Dashboard data computed. */
                        message: string;
                        data: {
                            widgets: components["schemas"]["WidgetResult"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    indexWidgets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Widgets retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Widgets retrieved. */
                        message: string;
                        data: {
                            widgets: components["schemas"]["Widget"][];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storeWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetInput"];
            };
        };
        responses: {
            /** @description Widget created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Widget created. */
                        message: string;
                        data: {
                            widget: components["schemas"]["Widget"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    destroyWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
                widget_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Widget deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_uuid: string;
                widget_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetUpdateInput"];
            };
        };
        responses: {
            /** @description Widget updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Widget updated. */
                        message: string;
                        data: {
                            widget: components["schemas"]["Widget"];
                        };
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        message: string;
                        data: {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
    };
}
